// src/components/Error.tsx
import { Button } from 'react-bootstrap';
import { useGlobalStateStore } from '../types/GlobalStateStore';
import { OutputData } from '../types/OutputData';

function Error(props: { output: React.MutableRefObject<OutputData | null> }) {
  const zustand = useGlobalStateStore();

  const error = props.output.current?.get('error') as string;
  return (
    <>
      <h2>Fehler</h2>
      <p>{error}</p>
      <p>
        <Button type='button' onClick={zustand.init}>
          Reset
        </Button>
      </p>
    </>
  );
}

export default Error;

// src/components/Error.svelte
<script lang="ts">
    import { globalState } from '../utils/state';
    import type { OutputData } from '../utils/types';
    export let output: OutputData;
    const error = output?.get('error') as string ?? 'unbekannter Fehler';
</script>

<h2>Fehler</h2>
<p>{error}</p>
<p>
  <button type="button" on:click={() => globalState.set('INIT')}>Reset</button>
</p>
