// src/components/ImgFigure.svelte
<script lang="ts">
  import type { FileInfos } from "../utils/types";
  import readableFileSize from "../utils/readableFileSize";

  export let image: [
    handler: string,
    fileinfos: { fileinfos?: FileInfos; source: string }
  ];
</script>

<figure class="figure">
  <img
    class="figure-img img-fluid"
    id={image[0]}
    src={image[1].source}
    alt={image[1].fileinfos?.filename}
  />
  <figcaption class="figure-caption">
    <a href={image[1].source} download={image[1].fileinfos?.filename}>
      {image[1].fileinfos?.filename}
    </a>
    <br />
    {#if image[0] === 'inputfile'}
      Originaldatei |
    {/if}
    {#if image[1].fileinfos?.quality}
      Qualität: {image[1].fileinfos.quality} |
    {/if}
    Größe: {readableFileSize(image[1].fileinfos?.filesize ?? 0)} kiB
  </figcaption>
</figure>

<style>
  figure {
    position: relative;
    margin-bottom: 30px;
  }

  figure img {
    width: 100%;
  }

  figcaption {
    background-color: rgba(211, 211, 211, 0.5);
    padding: 0.7rem;
    position: absolute;
    top: 1rem;
    left: 25%;
    width: 50%;
    border-radius: 15px;
    color: #000 !important;
  }
  figcaption a[download] {
    color: inherit;
    background-image: url("file-earmark-arrow-down.svg");
    background-position: left top;
    background-repeat: no-repeat;
    padding-left: 20px;
  }
</style>

// src/components/ImgFigure.tsx
import { Figure } from 'react-bootstrap';
import './ImgFigure.css';
import readableFilesize from '../readableFilesize';
import { FileInfos } from '../types/FileFragment';

function ImgFigure(props: { image: [handler: string, fileinfos: { fileinfos?: FileInfos; source: string }] }) {
  return (
    <Figure>
      <Figure.Image fluid id={props.image[0]} src={props.image[1].source} alt={props.image[1].fileinfos?.filename} />
      <Figure.Caption>
        <a href={props.image[1].source} download={props.image[1].fileinfos?.filename}>
          {props.image[1].fileinfos?.filename}
        </a>
        <br />
        {props.image[1].fileinfos?.quality && <>Qualität: {props.image[1].fileinfos.quality} | </>}
        Größe: {readableFilesize(props.image[1].fileinfos?.filesize as number)} kiB
      </Figure.Caption>
    </Figure>
  );
}

export default ImgFigure;
